version: '3.7'

services: 
  app: 
    image: client_table
    ports: 
      - 80:80
      - 443:443
    working_dir: /app
    volumes: 
      - ../httpd-cert:/etc/ssl
      - ./htpasswd:/etc/nginx/htpasswd
    depends_on:
      - proxy
  
  proxy: 
    image: node:12-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 3001:3001
    working_dir: /proxy
    volumes: 
      - ./proxy:/proxy
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: q12we34rt5
      MYSQL_DB: cafe_tables
      CERT: ./cert/elstestzone.ru_2021-09-28-06-48_36.crt
      KEY: ./cert/elstestzone.ru_2021-09-28-06-48_36.key
      PORT_PROXY: 3001
    depends_on:
      - mysql
  
  mysql: 
    image: mysql:5.7
    volumes:
      - table-mysql-data:/var/lib/mysql 
      - ./mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: q12we34rt5
      MYSQL_DATABASE: cafe_tables

volumes:
  table-mysql-data: